export const CAR_OPEN_REQUEST = "CAR_OPEN_REQUEST";
export const CAR_OPEN_SUCCESS = "CAR_OPEN_SUCCESS";
export const CAR_OPEN_FAIL = "CAR_OPEN_FAIL";

export const CAR_CLOSE_REQUEST = "CAR_CLOSE_REQUEST";
export const CAR_CLOSE_SUCCESS = "CAR_CLOSE_SUCCESS";
export const CAR_CLOSE_FAIL = "CAR_CLOSE_FAIL";
