export const GATE_OPEN_REQUEST = "GATE_OPEN_REQUEST";
export const GATE_OPEN_SUCCESS = "GATE_OPEN_SUCCESS";
export const GATE_OPEN_FAIL = "GATE_OPEN_FAIL";

export const GATE_CLOSE_REQUEST = "GATE_CLOSE_REQUEST";
export const GATE_CLOSE_SUCCESS = "GATE_CLOSE_SUCCESS";
export const GATE_CLOSE_FAIL = "GATE_CLOSE_FAIL";
