export const LED_OPEN_CLOSE_REQUEST = "LED_OPEN_REQUEST";
export const LED_OPEN_CLOSE_SUCCESS = "LED_OPEN_SUCCESS";
export const LED_OPEN_CLOSE_FAIL = "LED_OPEN_FAIL";

export const LED_STATUS_REQUEST = "LED_STATUS_REQUEST";
export const LED_STATUS_SUCCESS = "LED_STATUS_SUCCESS";
export const LED_STATUS_FAIL = "LED_STATUS_FAIL";
