export const ROOF_OPEN_REQUEST = "ROOF_OPEN_REQUEST";
export const ROOF_OPEN_SUCCESS = "ROOF_OPEN_SUCCESS";
export const ROOF_OPEN_FAIL = "ROOF_OPEN_FAIL";

export const ROOF_CLOSE_REQUEST = "ROOF_CLOSE_REQUEST";
export const ROOF_CLOSE_SUCCESS = "ROOF_CLOSE_SUCCESS";
export const ROOF_CLOSE_FAIL = "ROOF_CLOSE_FAIL";
