export const TEMP_STATUS_REQUEST = "TEMP_STATUS_REQUEST";
export const TEMP_STATUS_SUCCESS = "TEMP_STATUS_SUCCESS";
export const TEMP_STATUS_FAIL = "TEMP_STATUS_FAIL";

export const TEMP_DATA_REQUEST = "TEMP_DATA_REQUEST";
export const TEMP_DATA_SUCCESS = "TEMP_DATA_SUCCESS";
export const TEMP_DATA_FAIL = "TEMP_DATA_FAIL";
